# Datos de identificación del proyecto
spring.application.name=backend-synapse
server.port=8080

# Conexión a la base de datos (POSTGRESQL)
# Utiliza variables de entorno si están disponibles, de lo contrario, usa valores locales
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/synapse}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
# Configuración de Hibernate DDL auto (puede ser 'update', 'create', 'create-drop', 'validate', o 'none')
spring.jpa.hibernate.ddl-auto=validate

# Mostrar las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar el modo "open-in-view" para evitar problemas de LazyInitializationException
spring.jpa.open-in-view=false
