# En este caso utilizar 'update' (para ir actualizando pero sin perder datos)
# Por otro lado se puede usar 'create' cuando se quiera borrar una columna o un dato. El problema esque se perderan datos.
spring.jpa.hibernate.ddl-auto=update


# Mostrar las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${postgres_db:synapse_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# Configuración de JWT para la seguidad de los tokens
security.jwt.secret-key=${JWT_SECRET_KEY:WRRZ37iivzrpyivAHbyjfJDWw+uHN8RHOVkdhuvgeyA8/pBnRj6PGIEYeBDT1Htl8syGLn6BD49l1hBEWBsLlA==}
security.jwt.algorithm=${JWT_ALGORITHM:HS512}
security.jwt.expiration=${JWT_EXPIRATION:3600000}
security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Cloudflare R2 / AWS S3 Config
cloudflare.r2.endpoint=${CLOUDFLARE_ACOUNT}
cloudflare.r2.access-key=${CLOUDFLARE_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_SECRET_KEY}
cloudflare.r2.bucket-name=${CLOUDFLARE_BUCKET_NAME}
cloudflare.r2.public-url=${CLOUDFLARE_PUBLIC_ID}

# Tamaño máximo permitido para un solo archivo (ejemplo: 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
