# Valida si la base de datos concuerda con lo que esta codificado.
spring.jpa.hibernate.ddl-auto=validate

# Utiliza variables de entorno si están disponibles, de lo contrario, usa valores locales
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.algorithm=${JWT_ALGORITHM}
security.jwt.expiration=${JWT_EXPIRATION}
security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}