# Datos de identificación del proyecto
spring.application.name=backend-synapse
server.port=8080
spring.profiles.active=prod

# Driver y Dialecto (POSTGRESQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# Mostrar las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar el modo "open-in-view" para evitar problemas de LazyInitializationException
spring.jpa.open-in-view=false

# Configuración de Correo Electrónico (Gmail por defecto)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true