# En este caso utilizar 'update' (para ir actualizando pero sin perder datos)
# Por otro lado se puede usar 'create' cuando se quiera borrar una columna o un dato. El problema esque se perderan datos.
spring.jpa.hibernate.ddl-auto=update

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${postgres_db:synapse_db}
spring.datasource.username=${postgres_user:postgres}
spring.datasource.password=${postgres_password:postgres}

# Configuración de JWT para la seguidad de los tokens
security.jwt.secret-key=${JWT_SECRET_KEY:WRRZ37iivzrpyivAHbyjfJDWw+uHN8RHOVkdhuvgeyA8/pBnRj6PGIEYeBDT1Htl8syGLn6BD49l1hBEWBsLlA==}
security.jwt.algorithm=${JWT_ALGORITHM:HS512}
security.jwt.expiration=${JWT_EXPIRATION:3600000}
security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}