server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es crucial para aplicaciones SPA (React Router)
        # Redirige todo el tráfico que no encuentre un archivo estático a index.html
        try_files $uri $uri/ /index.html;
    }
}
